---
- name: Converge - E2E Tests
  hosts: localhost
  gather_facts: false
  vars:
    api_url: "http://localhost:8080"
    api_token: "{{ lookup('file', molecule_scenario_directory + '/.api-token') | trim }}"
  vars_files:
    - vars/test_data.yml
  collections:
    - remnawave.panel

  tasks:
    - name: Run config profile tests
      ansible.builtin.include_tasks: tasks/config_profile.yml

    - name: Run node tests
      ansible.builtin.include_tasks: tasks/node.yml

    - name: Run error handling tests
      ansible.builtin.include_tasks: tasks/error_handling.yml

    - name: Run cleanup tests
      ansible.builtin.include_tasks: tasks/cleanup.yml
