---
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory/
  env:
    ANSIBLE_FORCE_COLOR: "true"
  cfg:
    defaults:
      deprecation_warnings: false
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

scenario:
  name: e2e
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: ansible
