#!/usr/bin/python
# -*- coding: utf-8 -*-

# ⚠️ AUTOMATICALLY GENERATED - DO NOT EDIT
# Generated by remnawave-ansible-gen

"""Ansible module for managing Config Profile resources in Remnawave panel."""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: rw_config_profile
short_description: Manage Remnawave panel configuration profiles
version_added: "1.0.0"
description:
    - Create, update, and delete Config Profile resources in Remnawave panel.
    - Supports check mode for dry-run operations.
    - Implements idempotency by comparing desired state with current state.
options:
    api_url:
        description:
            - The URL of the Remnawave panel API.
            - Can be set via the C(REMNAWAVE_API_URL) environment variable.
        type: str
        required: true
    api_token:
        description:
            - The API token for authentication.
            - Can be set via the C(REMNAWAVE_API_TOKEN) environment variable.
        type: str
        required: true
        no_log: true
    state:
        description:
            - The desired state of the resource.
            - C(present) ensures the resource exists with the specified configuration.
            - C(absent) ensures the resource does not exist.
        type: str
        default: present
        choices:
            - present
            - absent
    uuid:
        description:
            - The unique identifier of the Config Profile.
            - Required when updating or deleting an existing resource by ID.
        type: str
        required: false
    name:
        description:
            - The name field
        type: str
        required: true
    config:
        description:
            - The config field
        type: dict
        required: true
author:
    - Remnawave Contributors
notes:
    - Supports check_mode for dry-run operations.
    - Uses the name field for resource lookup when uuid is not provided.
"""

EXAMPLES = r"""
- name: Create a new config profile
  remnawave.panel.rw_config_profile:
    api_url: "https://panel.example.com"
    api_token: "{{ api_token }}"
    state: present
    name: "example_value"
    config: "example_value"

- name: Update an existing config profile
  remnawave.panel.rw_config_profile:
    api_url: "https://panel.example.com"
    api_token: "{{ api_token }}"
    state: present
    uuid: "existing-uuid-here"
    name: "updated_value"
    config: "updated_value"

- name: Delete a config profile
  remnawave.panel.rw_config_profile:
    api_url: "https://panel.example.com"
    api_token: "{{ api_token }}"
    state: absent
    uuid: "uuid-to-delete"

- name: Delete a config profile by name
  remnawave.panel.rw_config_profile:
    api_url: "https://panel.example.com"
    api_token: "{{ api_token }}"
    state: absent
    name: "resource-name-to-delete"
"""

RETURN = r"""
changed:
    description: Whether the resource was changed.
    type: bool
    returned: always
response:
    description: The API response containing the resource data.
    type: dict
    returned: when resource is created or updated
    sample:
        uuid: "550e8400-e29b-41d4-a716-446655440000"
        name: "example"
        config: "example"
diff:
    description: The difference between desired and current state.
    type: dict
    returned: when in check_mode and changes would be made
    contains:
        before:
            description: The current state of the resource.
            type: dict
        after:
            description: The desired state of the resource.
            type: dict
msg:
    description: A message describing the result of the operation.
    type: str
    returned: always
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.remnawave.panel.plugins.module_utils.remnawave import (
    RemnawaveClient,
    camel_to_snake_dict,
    recursive_diff,
    snake_to_camel_dict,
)


def build_payload(params, fields):
    """Build the API payload from module parameters."""
    payload = {}
    for field in fields:
        snake_name = field["snake_name"]
        camel_name = field["name"]
        value = params.get(snake_name)
        if value is not None:
            # Convert nested dict keys from snake_case to camelCase
            if isinstance(value, dict):
                value = snake_to_camel_dict(value)
            elif isinstance(value, list):
                value = [snake_to_camel_dict(item) if isinstance(item, dict) else item for item in value]
            payload[camel_name] = value
    return payload


def run_module():
    """Main module execution."""
    # Define argument spec
    module_args = dict(
        api_url=dict(type="str", required=True, fallback=(lambda: None, [])),
        api_token=dict(type="str", required=True, no_log=True, fallback=(lambda: None, [])),
        state=dict(type="str", default="present", choices=["present", "absent"]),
        uuid=dict(type="str", required=False),
        name=dict(
            type="str",
            required=False,
        ),
        config=dict(
            type="dict",
            required=False,
        ),
    )

    # Field definitions for payload building
    fields = [
        {"snake_name": "name", "name": "name"},
        {"snake_name": "config", "name": "config"},
    ]

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True,
        required_if=[
            ("state", "present", ("name",), False),
        ],
    )

    # Initialize client
    client = RemnawaveClient(
        api_url=module.params["api_url"],
        api_token=module.params["api_token"],
        module=module,
    )

    state = module.params["state"]
    resource_id = module.params.get("uuid")
    lookup_value = module.params.get("name")

    result = dict(
        changed=False,
        msg="",
    )

    try:
        # Find existing resource
        existing = None
        if resource_id:
            existing = client.get_one("/api/config-profiles/{uuid}", resource_id)
        elif lookup_value:
            all_resources = client.get_all("/api/config-profiles")
            for resource in all_resources:
                if resource.get("name") == lookup_value:
                    existing = resource
                    resource_id = resource.get("uuid")
                    break

        if state == "absent":
            if existing:
                if module.check_mode:
                    result["changed"] = True
                    result["msg"] = "Config Profile would be deleted"
                    result["diff"] = {"before": camel_to_snake_dict(existing), "after": {}}
                else:
                    client.delete("/api/config-profiles/{uuid}", resource_id)
                    result["changed"] = True
                    result["msg"] = "Config Profile deleted successfully"
            else:
                result["msg"] = "Config Profile does not exist"
            module.exit_json(**result)

        # state == "present"
        payload = build_payload(module.params, fields)

        if not existing:
            # CREATE
            if module.check_mode:
                result["changed"] = True
                result["msg"] = "Config Profile would be created"
                result["diff"] = {"before": {}, "after": camel_to_snake_dict(payload)}
            else:
                response = client.create("/api/config-profiles", payload)
                result["changed"] = True
                result["response"] = camel_to_snake_dict(response)
                result["msg"] = "Config Profile created successfully"
        else:
            # UPDATE - check if changes needed
            diff = recursive_diff(payload, existing)
            if diff:
                if module.check_mode:
                    result["changed"] = True
                    result["msg"] = "Config Profile would be updated"
                    result["diff"] = {
                        "before": camel_to_snake_dict(existing),
                        "after": camel_to_snake_dict({**existing, **payload}),
                    }
                else:
                    # Add ID to payload for update
                    payload["uuid"] = resource_id
                    response = client.update("/api/config-profiles/{uuid}", payload, resource_id)
                    result["changed"] = True
                    result["response"] = camel_to_snake_dict(response)
                    result["msg"] = "Config Profile updated successfully"
            else:
                result["response"] = camel_to_snake_dict(existing)
                result["msg"] = "Config Profile is already in desired state"

        module.exit_json(**result)

    except Exception as e:
        result.pop("msg", None)  # Remove msg to avoid duplicate keyword argument
        module.fail_json(msg=str(e), **result)


def main():
    """Entry point."""
    run_module()


if __name__ == "__main__":
    main()
