---
- name: Converge
  hosts: localhost
  gather_facts: false
  vars:
    api_url: "http://localhost:4010"
    api_token: "test-token"
  collections:
    - remnawave.panel

  tasks:
    # ===========================================
    # Test Config Profile CRUD
    # ===========================================

    - name: Create a config profile
      remnawave.panel.config_profile:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: present
        name: "Test Profile"
        config: {}
      register: create_profile_result

    - name: Assert config profile was created
      ansible.builtin.assert:
        that:
          - create_profile_result.changed
          - create_profile_result.response is defined
        fail_msg: "Config profile creation failed"

    - name: Create same config profile again (idempotency test)
      remnawave.panel.config_profile:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: present
        name: "Test Profile"
        config: {}
      register: idempotent_profile_result

    - name: Assert config profile is idempotent
      ansible.builtin.assert:
        that:
          - not idempotent_profile_result.changed
        fail_msg: "Config profile should be idempotent"

    # ===========================================
    # Test Node CRUD
    # ===========================================

    - name: Create a node
      remnawave.panel.node:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: present
        name: "Test Node"
        address: "10.0.0.1"
        port: 443
        config_profile:
          active_config_profile_uuid: "{{ create_profile_result.response.uuid | default('00000000-0000-0000-0000-000000000000') }}"
          active_inbounds: []
      register: create_node_result

    - name: Assert node was created
      ansible.builtin.assert:
        that:
          - create_node_result.changed
          - create_node_result.response is defined
        fail_msg: "Node creation failed"

    - name: Create same node again (idempotency test)
      remnawave.panel.node:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: present
        name: "Test Node"
        address: "10.0.0.1"
        port: 443
        config_profile:
          active_config_profile_uuid: "{{ create_profile_result.response.uuid | default('00000000-0000-0000-0000-000000000000') }}"
          active_inbounds: []
      register: idempotent_node_result

    - name: Assert node is idempotent
      ansible.builtin.assert:
        that:
          - not idempotent_node_result.changed
        fail_msg: "Node should be idempotent"

    - name: Update node address
      remnawave.panel.node:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: present
        name: "Test Node"
        address: "10.0.0.2"
        port: 443
        config_profile:
          active_config_profile_uuid: "{{ create_profile_result.response.uuid | default('00000000-0000-0000-0000-000000000000') }}"
          active_inbounds: []
      register: update_node_result

    - name: Assert node was updated
      ansible.builtin.assert:
        that:
          - update_node_result.changed
        fail_msg: "Node update failed"

    # ===========================================
    # Test Check Mode
    # ===========================================

    - name: Create node in check mode
      remnawave.panel.node:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: present
        name: "Check Mode Node"
        address: "10.0.0.100"
        config_profile:
          active_config_profile_uuid: "{{ create_profile_result.response.uuid | default('00000000-0000-0000-0000-000000000000') }}"
          active_inbounds: []
      check_mode: true
      register: check_mode_result

    - name: Assert check mode reports changed
      ansible.builtin.assert:
        that:
          - check_mode_result.changed
          - check_mode_result.diff is defined
        fail_msg: "Check mode should report changed for new resource"
