---
- name: Destroy
  hosts: localhost
  gather_facts: false
  vars:
    api_url: "http://localhost:4010"
    api_token: "test-token"
  collections:
    - remnawave.panel

  tasks:
    - name: Delete test node
      remnawave.panel.rw_node:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: absent
        name: "Test Node"
      ignore_errors: true

    - name: Delete test config profile
      remnawave.panel.rw_config_profile:
        api_url: "{{ api_url }}"
        api_token: "{{ api_token }}"
        state: absent
        name: "Test Profile"
      ignore_errors: true
