---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: localhost
    localhost: true
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "~/.ansible/collections"
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
        api_url: "http://localhost:4010"
        api_token: "test-token"
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
