namespace: remnawave
name: panel
version: 1.0.0
readme: README.md
authors:
  - Remnawave Contributors
description: Ansible collection for managing Remnawave panel resources
license_file: LICENSE
dependencies: {}
repository: https://github.com/remnawave/ansible-collection
documentation: https://github.com/remnawave/ansible-collection
tags:
  - remnawave
  - vpn
  - panel
  - infrastructure
