namespace: remnawave
name: panel
version: 2.5.3
readme: README.md
authors:
  - Remnawave Contributors
description: Ansible collection for managing Remnawave panel resources
license:
  - MIT
dependencies: {}
repository: https://github.com/remnawave/ansible-collection
documentation: https://github.com/remnawave/ansible-collection
tags:
  - remnawave
  - vpn
  - panel
  - infrastructure
