---
- name: Destroy E2E environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run E2E teardown script
      ansible.builtin.command:
        cmd: "{{ playbook_dir }}/../../scripts/e2e-teardown.sh"
      register: teardown_result
      changed_when: true
      ignore_errors: true

    - name: Display teardown output
      ansible.builtin.debug:
        var: teardown_result.stdout_lines
      when: teardown_result.stdout_lines is defined
