namespace: remnawave
name: panel
version: 0.1.0
readme: README.md
authors:
  - Ilya Gulya
description: Ansible collection for managing Remnawave panel resources
license:
  - MIT
dependencies: {}
repository: https://github.com/remnawave/ansible-collection
documentation: https://github.com/remnawave/ansible-collection
tags:
  - remnawave
  - vpn
  - panel
  - infrastructure
